{% set name = "itables" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/itables-{{ version }}.tar.gz
  sha256: dae51872275f7d2a7be7159c280a67ae369ec31bb0d3b87042c5919f6de201a3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - nodejs
    - python >=3.8
    - python-build
    - hatch-jupyter-builder
    - hatchling
    - pip
  run:
    - ipython
    - pandas
    - numpy
    - python >=3.7

test:
  imports:
    - itables
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mwouts/itables
  doc_url: https://mwouts.github.io/itables/quick_start.html
  summary: Pandas and Polar DataFrames as interactive DataTables
  license: MIT
  license_file:
    - LICENSE
    - LICENSE_jquery.txt
    - LICENSE_datatables-net.txt
  description: >-
    This packages changes how Pandas and Polars DataFrames are rendered in Jupyter Notebooks.
    With `itables` you can display your tables as interactive [DataTables](https://datatables.net/)
    that you can sort, paginate, scroll or filter.

    ITables is just about how tables are displayed. You can turn it on and off in just two lines,
    with no other impact on your data workflow.

    The `itables` package only depends on `numpy`, `pandas` and `IPython`
    which you must already have if you work with Pandas in Jupyter (add `polars`, `pyarrow` if you
    work with Polars DataFrames).

extra:
  recipe-maintainers:
    - mwouts
    - asford
