{% set name = "itables" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/itables-{{ version }}.tar.gz
  sha256: dae51872275f7d2a7be7159c280a67ae369ec31bb0d3b87042c5919f6de201a3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - nodejs
    - python >=3.8
    - python-build
    - hatch-jupyter-builder
    - hatchling
    - pip
  run:
    - ipython
    - pandas
    - numpy
    - python >=3.7

test:
  imports:
    - itables
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mwouts/itables
  summary: Pandas and Polar DataFrames as interactive DataTables
  license: MIT
  license_file:
    - LICENSE
    - LICENSE_jquery.txt
    - LICENSE_datatables-net.txt

extra:
  recipe-maintainers:
    - mwouts
    - asford
